# Generated by Django 2.2.12 on 2021-09-03 05:29

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=13)),
                ('content', models.TextField()),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_tag', models.CharField(blank=True, max_length=200, null=True)),
                ('bannerimage', models.FileField(blank=True, null=True, upload_to='images/')),
                ('thumbnailimg', models.ImageField(blank=True, null=True, upload_to='thumbnailimg/')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('0', 'Draft'), ('1', 'Publish'), ('2', 'Withdrawn')], default=0, max_length=10)),
                ('snippets', models.CharField(default='Give the snapshot to blog. ', max_length=200)),
                ('view', models.IntegerField(default=0)),
                ('view_post_bool', models.BooleanField(default=False)),
                ('likes', models.ManyToManyField(blank=True, default=None, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('userprofileimg', models.ImageField(default='profileimage/einstein.png', upload_to='profileimage/')),
                ('userbannerimage', models.ImageField(default='userbannerimage/1543903484career-launcher-logo.png', upload_to='userbannerimage/')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=250, null=True)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
                ('user_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='Profileinfoform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('middlename', models.CharField(max_length=50, null=True)),
                ('lastname', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=150, null=True)),
                ('phoneno1', models.CharField(max_length=13, null=True)),
                ('phoneno2', models.CharField(max_length=13, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=7)),
                ('address', models.CharField(max_length=250, null=True)),
                ('permanentaddress', models.CharField(max_length=250, null=True)),
                ('country', models.CharField(max_length=30, null=True)),
                ('state', models.CharField(max_length=30, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('pincode', models.ImageField(max_length=10, null=True, upload_to='')),
                ('dob', models.DateField(null=True)),
                ('updated_on', models.DateField(auto_now_add=True)),
                ('about', models.CharField(max_length=250, null=True)),
                ('university', models.CharField(max_length=150, null=True)),
                ('startdate', models.DateField(null=True)),
                ('completiondate', models.DateField(null=True)),
                ('unicity', models.CharField(max_length=30, null=True)),
                ('college', models.CharField(max_length=150, null=True)),
                ('collegestartdate', models.DateField(null=True)),
                ('collegecompletiondate', models.DateField(null=True)),
                ('collegecity', models.CharField(max_length=30, null=True)),
                ('school', models.CharField(max_length=150, null=True)),
                ('schoolstartdate', models.DateField(null=True)),
                ('schoolcompletiondate', models.DateField(null=True)),
                ('schoolcity', models.CharField(max_length=30, null=True)),
                ('company', models.CharField(max_length=30, null=True)),
                ('experience', models.IntegerField(default=0, null=True)),
                ('companycity', models.CharField(max_length=30, null=True)),
                ('technicalskills', models.CharField(max_length=200, null=True)),
                ('hobbies', models.CharField(max_length=200, null=True)),
                ('abouthobbies', models.CharField(max_length=200, null=True)),
                ('website', models.CharField(max_length=150, null=True)),
                ('facebook', models.CharField(max_length=100, null=True)),
                ('twitter', models.CharField(max_length=100, null=True)),
                ('youtube', models.CharField(max_length=100, null=True)),
                ('linkedin', models.CharField(max_length=100, null=True)),
                ('puser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bloglikes',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('post_bool', models.CharField(choices=[('True', 'True'), ('False', 'False')], default=False, max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.BlogComment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
