# Generated by Django 2.2.12 on 2021-09-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='snippets',
            field=models.CharField(blank=True, default='Give the snapshot to blog. ', max_length=200, null=True),
        ),
    ]
