# Generated by Django 2.2.12 on 2021-09-06 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_snippets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfoform',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
    ]
