# Generated by Django 2.2.12 on 2021-09-07 07:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210906_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_category',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
