# Generated by Django 2.2.12 on 2021-09-07 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_add_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_category',
            old_name='slug',
            new_name='slug_cat',
        ),
    ]
